# Generated by Django 6.0.4 on 2026-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0002_bodegaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='banco_otro',
            field=models.CharField(blank=True, help_text='Completar solo si elegiste "Otro banco".', max_length=100, verbose_name='Banco (otro)'),
        ),
        migrations.AddField(
            model_name='abono',
            name='comprobante_url',
            field=models.URLField(blank=True, help_text='URL del comprobante de transferencia (Google Drive, WhatsApp, etc.).', verbose_name='Link del comprobante'),
        ),
        migrations.AddField(
            model_name='abono',
            name='factura_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos (factura)'),
        ),
        migrations.AddField(
            model_name='abono',
            name='factura_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula / RUC (factura)'),
        ),
        migrations.AddField(
            model_name='abono',
            name='factura_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico (factura)'),
        ),
        migrations.AddField(
            model_name='abono',
            name='factura_nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres (factura)'),
        ),
        migrations.AddField(
            model_name='abono',
            name='factura_realizada',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2, verbose_name='¿Factura realizada?'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='abono',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito / Payphone')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
