# Generated by Django 6.0.5 on 2026-05-22 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0006_retira_payphone_abonos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='reporte_actualizado',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de la última edición del reporte del técnico.', null=True, verbose_name='Reporte actualizado el'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='reporte_por',
            field=models.ForeignKey(blank=True, help_text='Técnico que escribió o actualizó el reporte por última vez (p. ej. desde el celular al escanear el QR).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_redactados', to=settings.AUTH_USER_MODEL, verbose_name='Reporte hecho por'),
        ),
    ]
