# Generated by Django 6.0.4 on 2026-05-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0007_ingresoequipo_reporte_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado / En diagnóstico'), ('en_reparacion', 'En reparación'), ('entregado', 'Entregado al cliente')], default='ingresado', max_length=30, verbose_name='Estado del equipo'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='estado_reparacion',
            field=models.CharField(choices=[('pendiente_retiro', '⏳ Reparado — pendiente de retiro'), ('cliente_no_acepta', '🚫 Cliente no quiso reparar'), ('no_reparable', '❌ No se pudo reparar'), ('reparado_parcial', '⚠️ Reparado parcialmente'), ('garantia', '🛡 Salida por garantía')], help_text='¿Cómo termina este equipo? La opción más común es "Retirado / Entregado conforme".', max_length=30, verbose_name='Estado de la salida'),
        ),
    ]
