# Generated by Django 6.0.4 on 2026-05-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0008_alter_ingresoequipo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='banco',
            field=models.CharField(blank=True, max_length=20, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='banco_otro',
            field=models.CharField(blank=True, help_text='Completar solo si elegiste "Otro banco".', max_length=100, verbose_name='Banco (otro)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='comprobante_url',
            field=models.URLField(blank=True, help_text='URL del comprobante de transferencia.', verbose_name='Link del comprobante'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='factura_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos (factura)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='factura_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula / RUC (factura)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='factura_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico (factura)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='factura_nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres (factura)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='factura_realizada',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2, verbose_name='¿Factura realizada?'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('payphone', 'Payphone / App'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Número de recibo'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='tarjeta_app',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tarjeta / App'),
        ),
        migrations.AlterField(
            model_name='ingresoequipo',
            name='subestado_reparacion',
            field=models.CharField(blank=True, choices=[('', '— Ninguno —'), ('espera_cliente', 'En reparación - Cliente'), ('espera_repuesto', 'En reparación - Repuestos')], default='', help_text='Solo aplica cuando el estado es "En reparación".', max_length=20, verbose_name='Detalle (En reparación)'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='estado_reparacion',
            field=models.CharField(choices=[('pendiente_retiro', '⏳ Reparado — pendiente de retiro'), ('cliente_no_acepta', '🚫 Cliente no quiso reparar'), ('no_reparable', '❌ No se pudo reparar'), ('reparado_parcial', '⚠️ Reparado parcialmente'), ('garantia', '🛡 Salida por garantía'), ('retirado', '✅ Retirado por el cliente'), ('chatarrerizacion', '♻️ Chatarrerización')], help_text='¿Cómo termina este equipo? La opción más común es "Retirado / Entregado conforme".', max_length=30, verbose_name='Estado de la salida'),
        ),
    ]
