# Generated by Django 6.0.4 on 2026-05-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0009_egreso_banco_egreso_banco_otro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='tarjeta_app',
            field=models.CharField(blank=True, choices=[('payphone', 'Payphone'), ('deuna', 'Deuna')], max_length=20, verbose_name='Tarjeta / App'),
        ),
    ]
