# Generated by Django 6.0.4 on 2026-05-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0010_alter_egreso_banco_alter_egreso_metodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaequipo',
            name='estado_reparacion',
            field=models.CharField(choices=[('pendiente_retiro', '⏳ Reparado — pendiente de retiro'), ('cliente_no_acepta', '🚫 Cliente no quiso reparar'), ('no_reparable', '❌ No se pudo reparar'), ('garantia', '🛡 Salida por garantía'), ('retirado', '✅ Retirado por el cliente'), ('chatarrerizacion', '♻️ Chatarrerización')], help_text='¿Cómo termina este equipo? La opción más común es "Retirado / Entregado conforme".', max_length=30, verbose_name='Estado de la salida'),
        ),
    ]
