# Generated by Django 6.0.4 on 2026-05-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0011_alter_salidaequipo_estado_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaequipo',
            name='banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='banco_otro',
            field=models.CharField(blank=True, help_text='Completar solo si elegiste "Otro banco".', max_length=100, verbose_name='Banco (otro)'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='comprobante_url',
            field=models.URLField(blank=True, help_text='URL del comprobante de transferencia (Google Drive, WhatsApp, etc.).', verbose_name='Link del comprobante'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='factura_apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos (factura)'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='factura_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula / RUC (factura)'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='factura_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='factura_nombres',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres (factura)'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='factura_realizada',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='¿Factura realizada?'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='numero_recibo',
            field=models.CharField(blank=True, help_text='Si se deja vacío y hay un cobro, se genera automáticamente.', max_length=30, verbose_name='Número de recibo'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='tarjeta_app',
            field=models.CharField(blank=True, choices=[('payphone', 'Payphone'), ('deuna', 'Deuna')], help_text='Solo cuando el método es Tarjeta o Payphone.', max_length=20, verbose_name='Tarjeta / App'),
        ),
    ]
