# Generated by Django 6.0.4 on 2026-06-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0013_alter_ingresoequipo_subestado_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='sede',
            field=models.CharField(choices=[('guayaquil', 'Guayaquil'), ('quito', 'Quito'), ('ventas', 'Venta de Productos')], default='guayaquil', help_text='Sede en la que se registró el equipo. Cada sede lleva su propia numeración.', max_length=20, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='metodo_pago_final',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito'), ('cortesia', 'Cortesía / sin cobro'), ('sin_pago', 'Sin pago (no aplica)')], default='efectivo', max_length=20, verbose_name='Método de pago del saldo final'),
        ),
    ]
