# Generated by Django 6.0.4 on 2026-06-09 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0014_alter_ingresoequipo_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='equipo_garantia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias_aplicadas', to='econotec.ingresoequipo', verbose_name='Aplica garantía a equipo'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='motivo_garantia',
            field=models.TextField(blank=True, verbose_name='Motivo de la garantía'),
        ),
        migrations.AlterField(
            model_name='ingresoequipo',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado / En diagnóstico'), ('en_reparacion', 'En reparación'), ('entregado', 'Entregado al cliente'), ('garantia', 'Garantía')], default='ingresado', max_length=30, verbose_name='Estado del equipo'),
        ),
    ]
