# Generated by Django 6.0.4 on 2026-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0015_ingresoequipo_equipo_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='subestado_entregado',
            field=models.CharField(blank=True, choices=[('', '— Ninguno —'), ('con_solucion', 'Con solución'), ('sin_solucion', 'Sin solución'), ('no_quiso_reparar', 'No quiso repararlo'), ('pendiente_retiro', 'Pendiente de retiro')], default='', help_text='Solo aplica cuando el estado es "Entregado al cliente".', max_length=20, verbose_name='Detalle (Entregado)'),
        ),
    ]
