# Generated by Django 6.0.4 on 2026-06-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0017_usuarioactividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sector',
            field=models.CharField(blank=True, choices=[('norte', 'Norte'), ('sur', 'Sur'), ('centro', 'Centro'), ('este', 'Este'), ('oeste', 'Oeste'), ('otro', 'Otro')], max_length=20, verbose_name='Sector'),
        ),
    ]
