# Generated by Django 6.0.4 on 2026-06-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0018_alter_cliente_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='equipo_garantia_manual',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Equipo de Garantía (Manual)'),
        ),
    ]
