# Generated by Django 6.0.4 on 2026-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0019_ingresoequipo_equipo_garantia_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioactividad',
            name='fecha_reinicio_perfil',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
