# Generated by Django 6.0.4 on 2026-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0020_usuarioactividad_fecha_reinicio_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='valor_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total acordado de la reparación. Déjelo vacío si aún no se cotiza.', max_digits=10, null=True, verbose_name='Valor acordado (USD)'),
        ),
    ]
