# Generated by Django 6.0.4 on 2026-06-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0021_alter_ingresoequipo_valor_acordado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_banco_otro',
            field=models.CharField(blank=True, help_text='Completar solo si elegiste "Otro banco".', max_length=100, verbose_name='Banco (otro)'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_comprobante_url',
            field=models.URLField(blank=True, help_text='URL del comprobante de transferencia (Google Drive, WhatsApp, etc.).', verbose_name='Link del comprobante'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito')], default='efectivo', max_length=20, verbose_name='Método de pago (inicial)'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_tarjeta_app',
            field=models.CharField(blank=True, choices=[('payphone', 'Payphone'), ('deuna', 'Deuna')], help_text='Solo cuando el método es Tarjeta o Payphone.', max_length=20, verbose_name='Tarjeta / App'),
        ),
    ]
