# Generated by Django 6.0.6 on 2026-07-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0022_ingresoequipo_anticipo_banco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaequipo',
            name='tecnico_reparo',
            field=models.ForeignKey(blank=True, help_text='Técnico responsable de la reparación. Este dato define quién suma puntos por esta salida en el perfil.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas_como_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Técnico que reparó'),
        ),
    ]
