# Generated by Django 6.0.6 on 2026-07-02 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0023_salidaequipo_tecnico_reparo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='Título del aviso')),
                ('mensaje', models.TextField(help_text='Texto que verán todos los usuarios en el inicio.', verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('info', 'Información (azul)'), ('exito', 'Éxito / positivo (verde)'), ('alerta', 'Alerta / atención (naranja)'), ('urgente', 'Urgente (rojo)')], default='info', max_length=10, verbose_name='Tipo / color del aviso')),
                ('fecha_inicio', models.DateField(help_text='Desde cuándo se muestra el aviso (inclusive).', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Hasta cuándo se muestra el aviso (inclusive).', verbose_name='Fecha final')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultar el aviso sin borrarlo.', verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Aviso del panel',
                'verbose_name_plural': 'Avisos del panel',
                'ordering': ['-fecha_inicio', '-creado'],
            },
        ),
    ]
