# Generated by Django 5.1.15 on 2026-07-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0024_avisopanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_banco_1',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_banco_2',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_metodo_1',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago Mixto')], max_length=20, verbose_name='Método de pago 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_metodo_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago Mixto')], max_length=20, verbose_name='Método de pago 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_monto_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='anticipo_monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto 2'),
        ),
        migrations.AlterField(
            model_name='ingresoequipo',
            name='anticipo_comprobante_url',
            field=models.URLField(blank=True, help_text='URL de la imagen/pdf del comprobante de pago inicial.', verbose_name='Link del comprobante'),
        ),
        migrations.AlterField(
            model_name='ingresoequipo',
            name='anticipo_metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago Mixto')], default='efectivo', max_length=20, verbose_name='Método de pago (inicial)'),
        ),
    ]
