# Generated by Django 5.1.15 on 2026-07-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0025_ingresoequipo_anticipo_banco_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago Mixto')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
    ]
