# Generated by Django 5.1.15 on 2026-07-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0026_alter_abono_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaequipo',
            name='banco_1',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco 1'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='banco_2',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco 2'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='metodo_1',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito'), ('mixto', 'Pago mixto (2 métodos)'), ('cortesia', 'Cortesía / sin cobro'), ('sin_pago', 'Sin pago (no aplica)')], max_length=20, verbose_name='Método 1'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='metodo_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito'), ('mixto', 'Pago mixto (2 métodos)'), ('cortesia', 'Cortesía / sin cobro'), ('sin_pago', 'Sin pago (no aplica)')], max_length=20, verbose_name='Método 2'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='monto_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto 1'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto 2'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='metodo_pago_final',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito'), ('mixto', 'Pago mixto (2 métodos)'), ('cortesia', 'Cortesía / sin cobro'), ('sin_pago', 'Sin pago (no aplica)')], default='efectivo', max_length=20, verbose_name='Método de pago del saldo final'),
        ),
    ]
