# Generated by Django 5.1.15 on 2026-07-06 21:44

from django.db import migrations, models


def copiar_pago_diagnostico(apps, schema_editor):
    IngresoEquipo = apps.get_model('econotec', 'IngresoEquipo')
    qs = IngresoEquipo.objects.filter(
        diagnostico_inmediato='si',
        valor_diagnostico__gt=0,
        abono_anticipo=0,
    )
    for ingreso in qs.iterator():
        ingreso.diagnostico_metodo = ingreso.anticipo_metodo
        ingreso.diagnostico_banco = ingreso.anticipo_banco
        ingreso.diagnostico_banco_otro = ingreso.anticipo_banco_otro
        ingreso.diagnostico_tarjeta_app = ingreso.anticipo_tarjeta_app
        ingreso.diagnostico_comprobante_url = ingreso.anticipo_comprobante_url
        ingreso.diagnostico_monto_1 = ingreso.anticipo_monto_1
        ingreso.diagnostico_metodo_1 = ingreso.anticipo_metodo_1
        ingreso.diagnostico_banco_1 = ingreso.anticipo_banco_1
        ingreso.diagnostico_monto_2 = ingreso.anticipo_monto_2
        ingreso.diagnostico_metodo_2 = ingreso.anticipo_metodo_2
        ingreso.diagnostico_banco_2 = ingreso.anticipo_banco_2
        ingreso.save(update_fields=[
            'diagnostico_metodo',
            'diagnostico_banco',
            'diagnostico_banco_otro',
            'diagnostico_tarjeta_app',
            'diagnostico_comprobante_url',
            'diagnostico_monto_1',
            'diagnostico_metodo_1',
            'diagnostico_banco_1',
            'diagnostico_monto_2',
            'diagnostico_metodo_2',
            'diagnostico_banco_2',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0027_salidaequipo_banco_1_salidaequipo_banco_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco del diagnóstico'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_banco_1',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco diagnóstico 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_banco_2',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco diagnóstico 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_banco_otro',
            field=models.CharField(blank=True, help_text='Completar solo si elegiste "Otro banco".', max_length=100, verbose_name='Banco del diagnóstico (otro)'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_comprobante_url',
            field=models.URLField(blank=True, help_text='URL de la imagen/pdf del comprobante de pago del diagnóstico.', verbose_name='Link del comprobante del diagnóstico'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago Mixto')], default='efectivo', max_length=20, verbose_name='Método de pago del diagnóstico'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_metodo_1',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago Mixto')], max_length=20, verbose_name='Método diagnóstico 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_metodo_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago Mixto')], max_length=20, verbose_name='Método diagnóstico 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_monto_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto diagnóstico 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto diagnóstico 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='diagnostico_tarjeta_app',
            field=models.CharField(blank=True, choices=[('payphone', 'Payphone'), ('deuna', 'Deuna')], help_text='Solo cuando el método es Tarjeta o Payphone.', max_length=20, verbose_name='Tarjeta / App del diagnóstico'),
        ),
        migrations.RunPython(copiar_pago_diagnostico, migrations.RunPython.noop),
    ]
