# Generated by Django 5.1.15 on 2026-07-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0028_ingresoequipo_diagnostico_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='subestado_entregado',
            field=models.CharField(blank=True, choices=[('', '— Ninguno —'), ('con_solucion', 'Con solución'), ('sin_solucion', 'Sin solución'), ('no_quiso_reparar', 'No quiso repararlo'), ('pendiente_retiro', 'Listo para entrega')], default='', help_text='Solo aplica cuando el estado es "Entregado al cliente".', max_length=20, verbose_name='Detalle (Entregado)'),
        ),
    ]
