# Generated by Django 5.1.15 on 2026-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0029_alter_ingresoequipo_subestado_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='subestado_reparacion',
            field=models.CharField(blank=True, choices=[('', '— Ninguno —'), ('en_reparacion', 'En reparación'), ('espera_cliente', 'En reparación - Cliente'), ('espera_repuesto', 'En reparación - Repuestos')], default='', help_text='Solo aplica cuando el estado es "En reparación".', max_length=20, verbose_name='Detalle (En reparación)'),
        ),
    ]
