# Generated by Django 5.1.15 on 2026-07-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0030_alter_ingresoequipo_subestado_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='serie',
            field=models.CharField(blank=True, max_length=200, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='ingresoequipo',
            name='modelo_serie',
            field=models.CharField(max_length=200, verbose_name='Modelo'),
        ),
    ]
