# Generated by Django 5.1.15 on 2026-07-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0033_alter_ingresoequipo_subestado_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioactividad',
            name='perfil_color_asesor',
            field=models.CharField(default='#0d47a1', max_length=7),
        ),
    ]
