# Generated by Django 5.1.15 on 2026-07-17 18:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0034_usuarioactividad_perfil_color_asesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaequipo',
            name='estado_reparacion',
            field=models.CharField(choices=[('pendiente_retiro', '⏳ Reparado — pendiente de retiro'), ('cliente_no_acepta', '🚫 Cliente no quiso reparar'), ('no_reparable', '❌ No se pudo reparar'), ('garantia', '🛡 Salida por garantía'), ('garantia_fallos_adicionales', '🛡 Salida + fallos adicionales'), ('retirado', '✅ Retirado por el cliente'), ('chatarrerizacion', '♻️ Chatarrerización')], help_text='¿Cómo termina este equipo? La opción más común es "Retirado / Entregado conforme".', max_length=30, verbose_name='Estado de la salida'),
        ),
        migrations.CreateModel(
            name='NotificacionAsesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fallos_adicionales', 'Garantía con fallos adicionales')], default='fallos_adicionales', max_length=30, verbose_name='Tipo de notificación')),
                ('valor_acordado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor acordado por fallos adicionales')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje para la asesora')),
                ('leida', models.BooleanField(default=False, verbose_name='Vista por la asesora')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Vista el')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('asesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_asesora', to=settings.AUTH_USER_MODEL, verbose_name='Asesora notificada')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_asesora_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Notificado por')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_asesora', to='econotec.ingresoequipo', verbose_name='Ingreso relacionado')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_asesora', to='econotec.salidaequipo', verbose_name='Salida relacionada')),
            ],
            options={
                'verbose_name': 'Notificación de asesora',
                'verbose_name_plural': 'Notificaciones de asesoras',
                'ordering': ['leida', '-creado'],
                'constraints': [models.UniqueConstraint(fields=('salida', 'tipo'), name='uniq_notificacion_asesora_salida_tipo')],
            },
        ),
    ]
