# Generated by Django 5.1.15 on 2026-07-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0035_alter_salidaequipo_estado_reparacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionasesora',
            name='tipo',
            field=models.CharField(choices=[('fallos_adicionales', 'Garantía con fallos adicionales'), ('revision_pendiente', 'Revisión pendiente de pago'), ('saldo_retiro', 'Equipo listo con saldo pendiente')], default='fallos_adicionales', max_length=30, verbose_name='Tipo de notificación'),
        ),
    ]
