# Generated by Django 5.1.15 on 2026-07-22 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0036_alter_notificacionasesora_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150)),
                ('momento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('ingreso', 'Ingreso de equipo'), ('ingreso_editado', 'Edición de equipo'), ('estado', 'Cambio de estado'), ('reporte', 'Reporte técnico'), ('valor_pendiente', 'Valor acordado pendiente'), ('salida', 'Salida de equipo'), ('salida_editada', 'Edición de salida'), ('venta_producto', 'Venta de producto'), ('venta_editada', 'Edición de venta'), ('abono', 'Abono'), ('abono_editado', 'Edición de abono'), ('eliminacion', 'Eliminación'), ('otro', 'Otra acción')], default='otro', max_length=40)),
                ('texto', models.TextField()),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('dedupe_key', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('abono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to='econotec.abono')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to='econotec.ingresoequipo')),
                ('salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_bitacora', to='econotec.salidaequipo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de técnico',
                'verbose_name_plural': 'Bitácora de técnicos',
                'ordering': ['momento', 'pk'],
                'indexes': [models.Index(fields=['user', 'momento'], name='econotec_bi_user_id_072322_idx'), models.Index(fields=['tipo', 'momento'], name='econotec_bi_tipo_6b3102_idx'), models.Index(fields=['codigo'], name='econotec_bi_codigo_2286df_idx')],
            },
        ),
    ]
