# Generated by Django 5.1.15 on 2026-07-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0037_bitacoratecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='firma_cliente',
            field=models.BooleanField(default=False, help_text='Indica si el cliente firmó digitalmente la solicitud de ingreso.', verbose_name='Firma del cliente'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='firma_cliente_imagen',
            field=models.TextField(blank=True, help_text='Firma digital capturada en formato PNG/base64.', verbose_name='Imagen de firma del cliente'),
        ),
    ]
