# Generated by Django 5.1.15 on 2026-07-22 17:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0038_ingresoequipo_firma_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('hora_inicio', models.TimeField(default=datetime.time(9, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(18, 0))),
                ('ultima_notificacion_laboral', models.DateTimeField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tecnico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='horario_laboral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario de técnico',
                'verbose_name_plural': 'Horarios de técnicos',
                'ordering': ['tecnico__first_name', 'tecnico__username'],
            },
        ),
    ]
