# Generated by Django 5.1.15 on 2026-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0039_horariotecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariotecnico',
            name='ultima_notificacion_fuera_laboral',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariotecnico',
            name='ultima_notificacion_fuera_motivo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
