# Generated by Django 5.1.15 on 2026-07-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0040_horariotecnico_ultima_notificacion_fuera_laboral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('impresora', 'Impresora'), ('laptop', 'Laptop'), ('pc', 'PC'), ('monitor', 'Monitor'), ('cpu', 'CPU'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('consola', 'Consola'), ('mando', 'Mando'), ('otro', 'Otros equipos')], max_length=20, verbose_name='Tipo de equipo'),
        ),
    ]
