# Generated by Codex on 2026-07-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0041_alter_ingresoequipo_tipo_equipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(choices=[('guayaquil', 'Guayaquil'), ('quito', 'Quito'), ('ventas', 'Venta de Productos')], max_length=20, verbose_name='Sede')),
                ('categoria', models.CharField(max_length=40, verbose_name='Categoría')),
                ('tipo', models.CharField(max_length=60, verbose_name='Tipo')),
                ('codigo', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Código QR')),
                ('producto', models.CharField(max_length=160, verbose_name='Producto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serie', models.CharField(blank=True, max_length=120, verbose_name='Serie')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='disponible', max_length=20, verbose_name='Estado')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('ubicacion', models.CharField(choices=[('guayaquil_norte', 'Guayaquil Norte'), ('guayaquil_centro', 'Guayaquil Centro'), ('quito', 'Quito')], max_length=30, verbose_name='Ubicación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventario_registrado', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Item de inventario',
                'verbose_name_plural': 'Items de inventario',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddIndex(
            model_name='inventarioitem',
            index=models.Index(fields=['sede', 'categoria', 'tipo'], name='econotec_in_sede_58fb50_idx'),
        ),
        migrations.AddIndex(
            model_name='inventarioitem',
            index=models.Index(fields=['codigo'], name='econotec_in_codigo_1bd48a_idx'),
        ),
    ]
