# Generated by Codex on 2026-07-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0042_inventarioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaInventarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad vendida')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inventario_item', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='ventas_asociadas',
                    to='econotec.inventarioitem',
                    verbose_name='Producto de inventario',
                )),
                ('venta', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='productos_inventario',
                    to='econotec.ingresoequipo',
                    verbose_name='Venta',
                )),
            ],
            options={
                'verbose_name': 'Producto de inventario vendido',
                'verbose_name_plural': 'Productos de inventario vendidos',
                'ordering': ['creado', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='ventainventarioitem',
            constraint=models.UniqueConstraint(
                fields=('venta', 'inventario_item'),
                name='uniq_producto_inventario_por_venta',
            ),
        ),
    ]
