# Generated by Django 5.1.15 on 2026-07-25 21:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0044_ingresoequipo_factura_venta_y_pagar_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo (USD)'),
        ),
        migrations.AddField(
            model_name='inventarioitem',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Precio de venta (USD)'),
        ),
    ]
