# Generated by Django 5.1.15 on 2026-07-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0045_inventario_precios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioitem',
            name='precio_venta',
        ),
    ]
