# Generated by Codex on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0046_remove_inventario_precio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='causa_no_disponible',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '—'),
                    ('bajo_pedido', 'Bajo pedido'),
                    ('defectuoso', 'Defectuoso'),
                    ('agotado', 'Agotado'),
                    ('obsoleto', 'Obsoleto'),
                ],
                default='',
                max_length=30,
                verbose_name='Causa de no disponibilidad',
            ),
        ),
    ]
