# Generated by Codex on 2026-07-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0047_inventarioitem_causa_no_disponible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionInventarioAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje para administración')),
                ('leida', models.BooleanField(default=False, verbose_name='Vista por administración')),
                ('leida_en', models.DateTimeField(blank=True, null=True, verbose_name='Vista el')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_inventario_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Notificado por')),
                ('inventario_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_admin', to='econotec.inventarioitem', verbose_name='Producto de inventario')),
            ],
            options={
                'verbose_name': 'Notificación de inventario para admin',
                'verbose_name_plural': 'Notificaciones de inventario para admin',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificacioninventarioadmin',
            constraint=models.UniqueConstraint(condition=models.Q(('leida', False)), fields=('inventario_item',), name='uniq_notificacion_inventario_pendiente'),
        ),
    ]
