# Generated by Django 5.1.15 on 2026-07-26 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0048_notificacioninventarioadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='banco_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Banco mixto 1'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='banco_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Banco mixto 2'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='ingreso_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egreso_compra', to='econotec.ingresoequipo', verbose_name='Ingreso de equipo comprado'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='metodo_1',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago mixto (2 métodos)')], max_length=20, verbose_name='Método mixto 1'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='metodo_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago mixto (2 métodos)')], max_length=20, verbose_name='Método mixto 2'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='monto_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto mixto 1'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto mixto 2'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='tarjeta_app_1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tarjeta / App mixta 1'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='tarjeta_app_2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tarjeta / App mixta 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_banco',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco de compra'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_banco_1',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco de compra 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_banco_2',
            field=models.CharField(blank=True, choices=[('pichincha', 'Banco Pichincha'), ('guayaquil', 'Banco Guayaquil'), ('produbanco', 'Produbanco'), ('pacifico', 'Banco Pacífico'), ('interbancaria', 'Interbancaria'), ('otro', 'Otro banco')], max_length=20, verbose_name='Banco de compra 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_banco_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco de compra (otro)'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_comprobante_url',
            field=models.URLField(blank=True, verbose_name='Comprobante de compra'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_metodo_1',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago mixto (2 métodos)')], max_length=20, verbose_name='Método de compra 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_metodo_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago mixto (2 métodos)')], max_length=20, verbose_name='Método de compra 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago mixto (2 métodos)')], default='efectivo', max_length=20, verbose_name='Método de pago de compra'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_monto_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de compra 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_monto_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de compra 2'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_tarjeta_app',
            field=models.CharField(blank=True, choices=[('payphone', 'Payphone'), ('deuna', 'Deuna')], max_length=20, verbose_name='Tarjeta / App de compra'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_tarjeta_app_1',
            field=models.CharField(blank=True, choices=[('payphone', 'Payphone'), ('deuna', 'Deuna')], max_length=20, verbose_name='Tarjeta / App de compra 1'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_tarjeta_app_2',
            field=models.CharField(blank=True, choices=[('payphone', 'Payphone'), ('deuna', 'Deuna')], max_length=20, verbose_name='Tarjeta / App de compra 2'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='metodo',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito / Débito'), ('mixto', 'Pago mixto (2 métodos)')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='ingresoequipo',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado / En diagnóstico'), ('en_reparacion', 'En reparación'), ('entregado', 'Entregado al cliente'), ('garantia', 'Garantía'), ('donado', 'Donado'), ('equipo_a_comprar', 'Equipo a comprar')], default='ingresado', max_length=30, verbose_name='Estado del equipo'),
        ),
    ]
