# Generated by Django 5.1.15 on 2026-07-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0049_egreso_banco_1_egreso_banco_2_egreso_ingreso_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='banco_otro_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco mixto 1 (otro)'),
        ),
        migrations.AddField(
            model_name='egreso',
            name='banco_otro_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco mixto 2 (otro)'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_banco_otro_1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco de compra 1 (otro)'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='compra_banco_otro_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Banco de compra 2 (otro)'),
        ),
    ]
