# Generated by Django 5.1.15 on 2026-07-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0050_egreso_banco_otro_1_egreso_banco_otro_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaequipo',
            name='valor_acordado_revision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo aplica cuando el estado de salida es Revisión.', max_digits=10, null=True, verbose_name='Valor acordado por revisión (USD)'),
        ),
        migrations.AlterField(
            model_name='ingresoequipo',
            name='subestado_entregado',
            field=models.CharField(blank=True, choices=[('', '— Ninguno —'), ('con_solucion', 'Con solución'), ('sin_solucion', 'Sin solución'), ('no_quiso_reparar', 'No quiso repararlo'), ('pendiente_retiro', 'Pendiente de retiro'), ('revision', 'Revisión')], default='', help_text='Solo aplica cuando el estado es "Entregado al cliente".', max_length=20, verbose_name='Detalle (Entregado)'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='estado_reparacion',
            field=models.CharField(choices=[('pendiente_retiro', '⏳ Reparado — pendiente de retiro'), ('revision', '🔎 Revisión'), ('cliente_no_acepta', '🚫 Cliente no quiso reparar'), ('no_reparable', '❌ No se pudo reparar'), ('garantia', '🛡 Salida por garantía'), ('garantia_fallos_adicionales', '🛡 Salida + fallos adicionales'), ('retirado', '✅ Retirado por el cliente'), ('chatarrerizacion', '♻️ Chatarrerización')], help_text='¿Cómo termina este equipo? La opción más común es "Retirado / Entregado conforme".', max_length=30, verbose_name='Estado de la salida'),
        ),
    ]
