# Generated by Django 5.1.15 on 2026-07-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0051_salidaequipo_valor_acordado_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioitem',
            name='observacion',
            field=models.TextField(blank=True, help_text='Nota interna opcional sobre el producto o pieza en inventario.', verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='ventainventarioitem',
            name='observacion',
            field=models.TextField(blank=True, help_text='Nota opcional de este producto dentro de la venta.', verbose_name='Observación'),
        ),
    ]
