# Generated by Codex on 2026-07-30

from django.db import migrations, models


def migrar_maquina_coser(apps, schema_editor):
    IngresoEquipo = apps.get_model('econotec', 'IngresoEquipo')
    variantes = {
        'maquina de coser',
        'maquina coser',
        'máquina de coser',
        'máquina coser',
    }
    for ingreso in IngresoEquipo.objects.filter(tipo_equipo='otro').exclude(tipo_equipo_otro=''):
        tipo_otro = ' '.join((ingreso.tipo_equipo_otro or '').strip().lower().split())
        if tipo_otro in variantes:
            ingreso.tipo_equipo = 'maquina_coser'
            ingreso.tipo_equipo_otro = ''
            ingreso.save(update_fields=['tipo_equipo', 'tipo_equipo_otro'])


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0052_inventarioitem_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='tipo_equipo',
            field=models.CharField(
                choices=[
                    ('impresora', 'Impresora'),
                    ('laptop', 'Laptop'),
                    ('pc', 'PC'),
                    ('monitor', 'Monitor'),
                    ('cpu', 'CPU'),
                    ('celular', 'Celular'),
                    ('tablet', 'Tablet'),
                    ('consola', 'Consola'),
                    ('mando', 'Mando'),
                    ('maquina_coser', 'Máquina de Coser'),
                    ('otro', 'Otros equipos'),
                ],
                max_length=20,
                verbose_name='Tipo de equipo',
            ),
        ),
        migrations.RunPython(migrar_maquina_coser, migrations.RunPython.noop),
    ]
