# Generated by Django 5.1.15 on 2026-07-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0053_alter_ingresoequipo_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoequipo',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'Ingresado / En diagnóstico'), ('en_reparacion', 'En reparación'), ('entregado', 'Entregado al cliente'), ('garantia', 'Garantía'), ('cortesia', 'Cortesía'), ('donado', 'Donado'), ('equipo_a_comprar', 'Equipo a comprar')], default='ingresado', max_length=30, verbose_name='Estado del equipo'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='estado_reparacion',
            field=models.CharField(choices=[('pendiente_retiro', '⏳ Reparado — pendiente de retiro'), ('revision', '🔎 Revisión'), ('cliente_no_acepta', '🚫 Cliente no quiso reparar'), ('no_reparable', '❌ No se pudo reparar'), ('garantia', '🛡 Salida por garantía'), ('garantia_fallos_adicionales', '🛡 Salida + fallos adicionales'), ('cortesia', 'Salida de cortesía'), ('retirado', '✅ Retirado por el cliente'), ('chatarrerizacion', '♻️ Chatarrerización')], help_text='¿Cómo termina este equipo? La opción más común es "Retirado / Entregado conforme".', max_length=30, verbose_name='Estado de la salida'),
        ),
    ]
