# Generated by Django 5.1.15 on 2026-07-30

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0054_alter_ingresoequipo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaequipo',
            name='aplica_valor_acordado_adicional',
            field=models.CharField(
                choices=[('si', 'Sí'), ('no', 'No')],
                default='no',
                help_text='Solo aplica cuando el equipo queda reparado y pendiente de retiro.',
                max_length=2,
                verbose_name='¿Aplica un valor acordado adicional?',
            ),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='motivo_valor_acordado_adicional',
            field=models.TextField(
                blank=True,
                help_text='Explicación del motivo por el que se acordó el valor adicional.',
                verbose_name='Motivo del valor acordado adicional',
            ),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='valor_acordado_adicional',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Valor adicional pendiente de pago acordado al finalizar la reparación.',
                max_digits=10,
                verbose_name='Valor acordado adicional (USD)',
            ),
        ),
    ]
