# Generated by Django 5.1.15 on 2026-08-12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0057_aclarar_resultado_tecnico_salida'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salidaequipo',
            options={
                'ordering': ['-fecha_salida', '-creado'],
                'verbose_name': 'Equipo finalizado',
                'verbose_name_plural': 'Equipos finalizados',
            },
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='estado_reparacion',
            field=models.CharField(
                choices=[
                    ('pendiente_retiro', '⏳ Reparado — pendiente de retiro'),
                    ('revision', '🔎 Revisión'),
                    ('cliente_no_acepta', '🚫 Cliente no quiso reparar'),
                    ('no_reparable', '❌ No se pudo reparar'),
                    ('garantia', '🛡 Garantía finalizada'),
                    ('garantia_fallos_adicionales', '🛡 Garantía finalizada + fallos adicionales'),
                    ('cortesia', 'Equipo de cortesía finalizado'),
                    ('retirado', '✅ Salió de la oficina'),
                    ('chatarrerizacion', '♻️ Chatarrerización'),
                ],
                help_text='¿Cómo termina este equipo? La opción más común es "Reparado — pendiente de retiro".',
                max_length=30,
                verbose_name='Resultado final del equipo',
            ),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='fecha_salida',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='ingreso',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='salida',
                to='econotec.ingresoequipo',
                verbose_name='Equipo finalizado',
            ),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='tecnico_reparo',
            field=models.ForeignKey(
                blank=True,
                help_text='Técnico responsable de la reparación. Este dato define quién recibe el resultado positivo o negativo de la finalización.',
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='salidas_como_tecnico',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Técnico que reparó',
            ),
        ),
        migrations.AlterField(
            model_name='salidaequipo',
            name='valor_final_cobrado',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Si ya está totalmente pagado, puedes dejar 0.',
                max_digits=10,
                verbose_name='Valor cobrado al finalizar (USD)',
            ),
        ),
    ]
