# Generated by Django 6.0.4 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0058_aclarar_finalizacion_y_salida_fisica'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioactividad',
            name='ocultar_guia_saldo_pendiente',
            field=models.BooleanField(
                default=False,
                verbose_name='No volver a mostrar la guía de saldo pendiente',
            ),
        ),
    ]
