# Generated by Django 5.1.15 on 2026-09-10 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0061_ampliar_cobro_adicional_finalizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, choices=[('heisenberg.jpg', 'Heisenberg'), ('harry-potter.jpg', 'Harry Potter'), ('master-chief.webp', 'Master Chief'), ('slytherin.jpg', 'Slytherin')], max_length=40)),
                ('portada', models.CharField(choices=[('aurora', 'Aurora'), ('oceano', 'Océano'), ('atardecer', 'Atardecer'), ('bosque', 'Bosque')], default='aurora', max_length=20)),
                ('biografia', models.TextField(blank=True, max_length=600)),
                ('musica', models.CharField(blank=True, max_length=240, verbose_name='Gustos musicales')),
                ('hobbies', models.CharField(blank=True, max_length=240)),
                ('cancion', models.CharField(blank=True, max_length=160, verbose_name='Canción favorita')),
                ('amigos', models.ManyToManyField(blank=True, to='econotec.perfilsocial')),
                ('me_gusta', models.ManyToManyField(blank=True, related_name='perfiles_favoritos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_social', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
