# Generated by Django 5.1.15 on 2026-09-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0062_perfilsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilsocial',
            name='avatar',
            field=models.CharField(blank=True, choices=[('heisenberg.jpg', 'Heisenberg'), ('harry-potter.jpg', 'Harry Potter'), ('master-chief.webp', 'Master Chief'), ('slytherin.jpg', 'Slytherin'), ('econotec.webp', 'Econotec')], max_length=40),
        ),
        migrations.AlterField(
            model_name='perfilsocial',
            name='portada',
            field=models.CharField(choices=[('aurora', 'Aurora'), ('oceano', 'Océano'), ('atardecer', 'Atardecer'), ('bosque', 'Bosque'), ('ciudad', 'Ciudad nocturna'), ('tecnologia', 'Tecnología')], default='aurora', max_length=20),
        ),
    ]
