# Generated by Django 5.1.15 on 2026-09-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0063_alter_perfilsocial_avatar_alter_perfilsocial_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilsocial',
            name='avatar',
            field=models.CharField(blank=True, choices=[('heisenberg.jpg', 'Heisenberg'), ('harry-potter.jpg', 'Harry Potter'), ('master-chief.webp', 'Master Chief'), ('slytherin.jpg', 'Slytherin'), ('econotec.webp', 'Econotec'), ('scorpions.jpg', 'Scorpions')], max_length=40),
        ),
    ]
