# Generated by Django 5.2.17 on 2026-09-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0064_alter_perfilsocial_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteAcceso',
            fields=[
                ('clave', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('expira', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
