# Generated by Django 5.2.17 on 2026-09-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0065_limite_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='fecha_alerta_reparacion',
            field=models.DateField(blank=True, help_text='Se actualiza automáticamente cuando el equipo entra a En reparación, Espera de cliente o Espera de repuesto.', null=True, verbose_name='Fecha de inicio del estado de reparación'),
        ),
    ]
