# Generated by Django 5.2.17 on 2026-10-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0066_alerta_reparacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono',
            name='aplica_retencion',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2, verbose_name='¿Aplicar retención?'),
        ),
        migrations.AddField(
            model_name='abono',
            name='retencion_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA de la factura con retención'),
        ),
        migrations.AddField(
            model_name='abono',
            name='retencion_iva_retenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retención del IVA'),
        ),
        migrations.AddField(
            model_name='abono',
            name='retencion_renta_retenida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retención de renta'),
        ),
        migrations.AddField(
            model_name='abono',
            name='retencion_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal a facturar'),
        ),
        migrations.AddField(
            model_name='abono',
            name='valor_con_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor con retención (total factura)'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='aplica_retencion',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2, verbose_name='¿Aplicar retención?'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='retencion_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA de la factura con retención'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='retencion_iva_retenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retención del IVA'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='retencion_renta_retenida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retención de renta'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='retencion_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal a facturar'),
        ),
        migrations.AddField(
            model_name='ingresoequipo',
            name='valor_con_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor con retención (total factura)'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='aplica_retencion',
            field=models.CharField(choices=[('no', 'No'), ('si', 'Sí')], default='no', max_length=2, verbose_name='¿Aplicar retención?'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='retencion_iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='IVA de la factura con retención'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='retencion_iva_retenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retención del IVA'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='retencion_renta_retenida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Retención de renta'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='retencion_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal a facturar'),
        ),
        migrations.AddField(
            model_name='salidaequipo',
            name='valor_con_retencion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor con retención (total factura)'),
        ),
    ]
