# Generated by Django 5.2.17 on 2026-10-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0067_retencion_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='a_domicilio',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2, verbose_name='A domicilio'),
        ),
    ]
