# Generated by Django 5.2.17 on 2026-10-09 20:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econotec', '0068_ingresoequipo_a_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoequipo',
            name='valor_domicilio',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor a domicilio'),
        ),
    ]
